general.import = [
    # "./themes/themes/xterm.toml"
    # "./themes/themes/kimbie_dark.toml"
    # "./themes/themes/hyper.toml"
    # "./themes/themes/chicago95.toml"
     # "./themes/themes/github_dark_default.toml" #not bad also
    "./themes/themes/dark_plus.toml"
]
[colors]
draw_bold_text_with_bright_colors = true


[colors.cursor]
# cursor = "#FFFFFF"
# text = "#000000"
text = "0x000000"
# cursor = "0x00ff00"
 # cursor = "0x00ffff"
 # cursor = "0xffff00"


[env]
TERM = "xterm-256color"
# TERM: screen-256color

# [font]
# size = 22
# normal.family= "Iosevka"
# bold.family = "Iosevka"
# italic.family = "Iosevka"

# [font.bold]
# family = "MonoLisa"
# style = "Bold"

# [font.italic]
# family = "MonoLisa"
# style = "italic"

[font]
# normal = { family = "MonoLisa", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# bold = { family = "MonoLisa", style = "SemiBold" }
# italic = { family = "MonoLisa", style = "Thin Italic" }
size = 13

# normal.family= "MesloLGS Nerd Font Mono"
# offset.x = 0
# offset.y = 0
# glyph_offset.x = 0
# glyph_offset.y = 0


[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 100000
# Scrolling distance multiplier.
multiplier = 3

# [terminal.shell]
# program= "/run/current-system/sw/bin/bash"
# args = ["--login", "-c", "/home/dinesh/script/session.sh"]

[window]
opacity = 1
blur = true
decorations = "full"
dynamic_title = true
# Square corners
# decorations = "none"
# decorations = "buttonless"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 185
lines = 40

# [window.position]
# x = 0
# y = 430

[selection]
save_to_clipboard = true
# scorlling enable

[cursor.style]
blinking = "always"
